export interface WorldProxy {
  /**
   * Checks if `text` can be placed in the world. Probably triggers some notification
   * in game if request is rejected.
   */
  // TODO somehow trigger notification event: cannot place comment here. notification is generated by game itself.
  requestForPlacingComment(text: string, size: number): boolean;

  getPlayer(): any; // TODO set actual type and add comments

  // Player: EffectManager, PlayerEntity

  // TODO move to World class
  // canPlaceComment(text: string): boolean {
  //   return true;
  // }
  //
  // sendNotification(text: string) {
  //
  // }
}
