import {LocallyOriginatedCommentEffectManager} from '../effect';
import {PlayerEntity} from '../entity/player';

export default interface UniverseProxy {
  /**
   * Checks if the shape of {@param commentText} can fit in its place.
   * Triggers some notification in game if request is rejected.
   */
  // TODO somehow trigger notification event: cannot place comment here. notification is generated by game itself.
  requestForPlacingComment(commentText: string, commentSize: number): boolean;

  getPlayer(): PlayerEntity;

  getEffectManager(): LocallyOriginatedCommentEffectManager;
}
